version: '3'

services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    volumes:
      - ./db-data:/var/lib/postgresql/data
  backend:
    build: .
    restart: on-failure
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
    depends_on:
      - db
#  frontend:
#    container_name: frontend
#    build: ./../frontend
#    volumes:
#      - './../frontend:/app'
#    ports:
#      - "3000:3000"
#    environment:
#      - CHOKIDAR_USEPOLLING=true
#    depends_on:
#      - db
#      - backend
#    networks:
#      - defaultNetwork
volumes:
  postgres-data:
networks:
  defaultNetwork:




